function [kodm_info] = ncar_info(dummy)

% kinst == 10 (Jicamarca)
        
    kodsi_code = [153 156 406 402 432 60 1030 1040 1050 1060];        
        
    kodmi_code = [120 110 1252 -1252 1241 -1241 1272 -1272 1282 -1282 ...
        3101 3102 3103 3104 3105 3106 3107 3108 32000 32001 ...
        500 -500 ...
        510 -510 560 -560 550 -550 660 -660 650 -650 3109 3110];
    
    kodmi_description = [ ...
        'Range                                '; ...
        'Altitude (height)                    '; ...
        'Direction 5 Ion velocity (perp north)'; ...
        'Direction 5 Ion velocity error       '; ...
        'Direction 4 Ion velocity (perp east) '; ...
        'Direction 4 Ion velocity error       '; ...
        'Direction 7 Ion velocity             '; ...
        'Direction 7 Ion velocity error       '; ...
        'Direction 8 Ion velocity             '; ...
        'Direction 8 Ion velocity error       '; ...
        'West rx A incoherent power lg(1+S/N) '; ... 
        'West rx A coherent power lg(1+S/N)   '; ...
        'West rx B incoherent power lg(1+S/N) '; ...
        'West rx B coherent power lg(1+S/N)   '; ...
        'East rx C incoherent power lg(1+S/N) '; ...
        'East rx C coherent power lg(1+S/N)   '; ...
        'East rx D incoherent power lg(1+S/N) '; ...
        'East rx D coherent power lg(1+S/N)   '; ...
        'West Beam Reduced chisquare          '; ...
        'East Beam Reduced chisquare          '; ...
        'Uncorrected electron dens            '; ...
        'Uncorrected Ne error                 '; ...        
        'Electron density                     '; ...
        'Electron density error               '; ...
        'Electron temperature                 '; ...
        'Te error                             '; ...
        'Ion temperature                      '; ...
        'Ti error                             '; ...       
        'Composition H+/Ne                    '; ...
        'H+/Ne error                          '; ...
        'Composition He+/Ne                   '; ...
        'He+/Ne error                         '; ...        
        'West Beam Reduced chisquare          '; ...
        'East Beam Reduced chisquare          '];
    
    kodmi_factor = [1.0 1.0 1.0e-2 1.0e-2 1.0e-1 1.0e-1 1.0e-2 1.0e-2 ...
        1.0e-2 1.0e-2 [1.E-03 1.E-03 1.E-03 1.E-03 1.E-03 1.E-03 ...
        1.E-03 1.E-03] .* 10 1.E-01 1.E-01 1.0E9 1.0E9 1.0E9 1.0E9 ...
        1.0 1.0 1.0 1.0 ...
        1.0E-0 1.0E-0 1.0E-0 1.0E-0 1.E-01 1.E-01];
    
    kodmi_units = ['km '; 'km '; 'm/s'; 'm/s'; 'm/s'; 'm/s'; 'm/s'; ...
        'm/s'; 'm/s'; 'm/s'; 'lg '; 'lg '; 'lg '; 'lg '; 'lg '; ...
        'lg '; 'lg '; 'lg '; '   '; '   '; 'm-3'; 'm-3'; 'm-3'; 'm-3'; ...
        'K  '; ...
        'K  '; 'K  '; 'K  '; '   '; '   '; '   '; '   '; '   '; '   '];
    
    kodmi_mnemonic = [ ...
        'gdalt    '; 'range    '; 'vipn     '; 'vipn_err '; ...
        'vipe     '; 'vipe_err '; 'vi7      '; 'vi7_err  '; ...
        'vi8      '; 'vi8_err  '; 'jrop01   '; 'jrop02   '; ...
        'jrop03   '; 'jrop04   '; 'jrop05   '; 'jrop06   '; ...
        'jrop07   '; 'jrop08   '; 'jro32000 '; 'jro32001 '; ...
        'un_ne    '; 'un_ne_err'; ...
        'ne       '; 'ne_err   '; 'te       '; 'te_err   '; ...
        'ti       '; 'ti_err   '; 'H        '; 'H_err    '; ...
        'He       '; 'He_err   '; 'jrop09   '; 'jrop10   '];
       
    kodm_info = struct('code', kodmi_code, 'description', kodmi_description, ...
        'factor', kodmi_factor, 'units', kodmi_units, 'mnemonic', kodmi_mnemonic);
