function output = read_msis_weboutput(filename)

    fid = fopen(filename, 'r');
        data_format = repmat('%f',1,20);
        tmp = textscan(fid, data_format, 'HeaderLines', 32);
    fclose(fid);
    
    output = struct('height', tmp{1,1}, 'O_density', tmp{1,2}, ...
        'N2_density', tmp{1,3}, 'O2_density', tmp{1,4}, ...
        'mass_density', tmp{1,5}, 'neutral_temp', tmp{1,6}, ...
        'exospheric_temp', tmp{1,7}, 'He_density', tmp{1,8}, ...
        'Ar_density', tmp{1,9}, 'H_density', tmp{1,10}, ...
        'N_density', tmp{1,11});
